apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 10
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hello-job
          image: busybox
          command: ["echo", "Hello I am from job"]
