apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oneapp
  labels:
    app: {{ .Release.Name }}-oneapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-oneapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-oneapp
    spec:
      containers:
        - name: oneapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
