{{- if .Values.multiPod.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    {{- include "k8s-exam.labels" . | nindent 4 }}
spec:
  containers:
    - name: alpha
      image: nginx
      env:
        - name: name
          value: alpha
    - name: beta
      image: busybox
      command: ["sleep", "4800"]
      env:
        - name: name
          value: beta
{{- end }}
