apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-shahar
spec:
  containers:
    - name: redis
      image: redis:alpine
      volumeMounts:
        - name: data
          mountPath: /data/redis
  volumes:
    - name: data
      emptyDir: {}
