apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-shahar
  labels:
    exam: q11
    app: redis-storage
spec:
  containers:
    - name: redis
      image: redis:alpine
      volumeMounts:
        - name: redis-data
          mountPath: /data/redis
  volumes:
    - name: redis-data
      emptyDir: {}
