apiVersion: v1
kind: Pod
metadata:
  name: use-pvspec-shahar
  labels:
    run: use-pv
spec:
  containers:
    - name: use-pv
      image: nginx
      volumeMounts:
        - name: pv-storage
          mountPath: /data
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pvc-1
  restartPolicy: Always
