apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    exam: configmap
    run: nginx
spec:
  restartPolicy: Never
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: keyvalcfgmap
